## Tests for nmf.ffb(method = "fiml") -- the two-stage likelihood-based
## estimator -- and for the bit-identity of the legacy method = "mu".

## Synthetic design: P1 = 6 outcomes generated by Q = 2 factors, P2 = 2
## exogenous drivers, N = 100; outcome y1 (factor 1) feeds back into factor 2.
make_ffb_data <- function() {
  set.seed(42)
  P1 <- 6; P2 <- 2; Q <- 2; N <- 100
  X <- matrix(0, P1, Q); X[1:3, 1] <- c(0.5, 0.3, 0.2); X[4:6, 2] <- c(0.4, 0.4, 0.2)
  T1 <- matrix(0, Q, P1); T1[2, 1] <- 0.6
  T2 <- matrix(c(1, 0.2, 0.3, 1), Q, P2)
  Y2 <- matrix(runif(P2 * N), P2, N); rownames(Y2) <- c("a", "b")
  U <- matrix(rnorm(Q * N, sd = 0.2), Q, N); E <- matrix(rnorm(P1 * N, sd = 0.05), P1, N)
  L <- solve(diag(P1) - X %*% T1)
  Y1 <- pmax(L %*% (X %*% (T2 %*% Y2 + U) + E), 0); rownames(Y1) <- paste0("y", 1:6)
  list(Y1 = Y1, Y2 = Y2, Q = Q)
}

legacy_fields <- c("X", "C1", "C2", "XC1", "XC2", "XC1.radius", "XC1.norm1",
                   "Leontief.inv", "M.model", "amplification", "amplification.bound",
                   "Q", "MAE", "effective.rank", "iter", "converged", "epsilon", "maxit")
fiml_fields <- c("method", "Phi", "psi", "loglik", "npar", "null", "full", "path",
                 "mask", "lambda1.selected", "support", "LR", "LR.df", "BIC", "AIC", "call")

test_that("nmf.ffb(method = 'fiml') fits, returns the legacy and the new fields, and DOT works", {
  skip_unless_full()
  d <- make_ffb_data()
  fit <- nmf.ffb(d$Y1, d$Y2, rank = d$Q)

  expect_s3_class(fit, "nmf.ffb"); expect_s3_class(fit, "nmf.sem")
  expect_identical(fit$method, "fiml")
  expect_true(all(legacy_fields %in% names(fit)))
  expect_true(all(fiml_fields %in% names(fit)))
  expect_null(fit$SC.map); expect_null(fit$SC.cov)
  expect_null(fit$objfunc); expect_null(fit$objfunc.full)

  ## shapes and constraints
  expect_equal(dim(fit$X), c(6, 2)); expect_equal(dim(fit$C1), c(2, 6)); expect_equal(dim(fit$C2), c(2, 2))
  expect_equal(unname(colSums(fit$X)), rep(1, 2), tolerance = 1e-12)
  expect_true(all(fit$C1 >= 0) && all(fit$C2 >= 0) && all(fit$psi > 0))
  expect_equal(dim(fit$Phi), c(2, 2)); expect_true(isSymmetric(fit$Phi, tol = 1e-10))
  expect_true(all(eigen(fit$Phi, only.values = TRUE)$values > 0))

  ## the block mask forbids self-loops: the dominant factor of every outcome is excluded
  dom <- apply(fit$X, 1, which.max)
  expect_true(all(fit$mask[cbind(dom, seq_len(6))] == 0))
  expect_equal(sum(fit$mask), 6)
  expect_true(all(fit$C1[fit$mask == 0] == 0))

  ## likelihood bookkeeping
  expect_gte(fit$full$loglik, fit$null$loglik - 1e-6)
  expect_gte(fit$loglik, fit$null$loglik - 1e-6)
  expect_named(fit$LR, c("full", "selected")); expect_named(fit$LR.df, c("full", "selected"))
  expect_equal(unname(fit$LR[["full"]]), 2 * (fit$full$loglik - fit$null$loglik))
  expect_equal(unname(attr(fit$LR, "df")), unname(fit$LR.df))
  expect_equal(fit$LR.df[["full"]], sum(fit$mask))
  expect_equal(fit$LR.df[["selected"]], sum(fit$support))
  expect_named(fit$BIC, c("null", "full", "selected")); expect_named(fit$AIC, c("null", "full", "selected"))
  expect_lte(fit$BIC[["selected"]], min(fit$BIC[["null"]], fit$BIC[["full"]]) + 1e-8)
  ## multi-start path: one row per (lambda1, start); "path" continuation is
  ## not available at the first penalty, so 1 + 3 + 4 * 7 + 1 rows
  expect_true(is.data.frame(fit$path))
  expect_named(fit$path, c("lambda1", "start", "support_id", "nnz", "rho", "loglik", "BIC",
                           "MAE", "pen.value", "duplicate"))
  expect_equal(fit$path$lambda1[1], 0); expect_true(is.infinite(tail(fit$path$lambda1, 1)))
  expect_equal(nrow(fit$path), 2 + 3 + 4 * 7)
  expect_identical(fit$starts, c("full", "path", "null", "soft"))
  expect_true(all(fit$path$start %in% fit$starts))
  ## "full" also labels the lambda1 = 0 row, "null" the lambda1 = Inf row
  expect_equal(unname(c(table(fit$path$start)[c("full", "null", "soft", "path")])), c(9L, 9L, 8L, 7L))
  expect_identical(fit$path$duplicate, duplicated(fit$path$support_id))
  expect_true(all(is.finite(fit$path$pen.value[is.finite(fit$path$lambda1) & fit$path$lambda1 > 0])))
  ## candidates: one row per distinct support, BIC minimized over all of them
  expect_true(is.data.frame(fit$candidates))
  expect_named(fit$candidates, c("support_id", "nnz", "rho", "loglik", "BIC", "MAE",
                                 "lambda1.first", "start.first", "selected"))
  expect_equal(fit$candidates$support_id, seq_len(nrow(fit$candidates)))
  expect_false(any(duplicated(fit$candidates$support_id)))
  expect_true(all(fit$path$support_id %in% fit$candidates$support_id))
  expect_length(fit$supports, nrow(fit$candidates))
  expect_equal(fit$candidates$nnz, vapply(fit$supports, sum, numeric(1)))
  expect_true(all(vapply(fit$supports, function(s) all(!s[fit$mask == 0]), logical(1))))
  expect_true(any(fit$candidates$nnz == 0) && any(fit$candidates$nnz == sum(fit$mask)))
  expect_equal(sum(fit$candidates$selected), 1L)
  expect_equal(fit$candidates$support_id[fit$candidates$selected], fit$support.selected)
  expect_equal(fit$BIC[["selected"]], min(fit$candidates$BIC))
  expect_lte(fit$BIC[["selected"]], min(fit$path$BIC) + 1e-8)
  expect_equal(fit$support, fit$supports[[fit$support.selected]])
  expect_equal(fit$lambda1.selected, fit$candidates$lambda1.first[fit$support.selected])
  expect_true(fit$lambda1.selected %in% fit$path$lambda1)
  ## every candidate BIC is consistent with its loglik and nnz
  expect_equal(fit$candidates$BIC,
               -2 * fit$candidates$loglik + log(100) * (fit$candidates$nnz + fit$null$npar))
  expect_equal(fit$null$C2, fit$null$C2 * 1)   # exists and numeric
  expect_equal(dim(fit$null$M.model), c(6, 2))

  ## S3 verbs and DOT on all three fits
  expect_output(print(fit)); expect_output(print(summary(fit)))
  expect_s3_class(nmf.ffb.DOT(fit), "nmfkc.DOT")
  expect_s3_class(nmf.ffb.DOT(fit, model = "null"), "nmfkc.DOT")
  expect_s3_class(nmf.ffb.DOT(fit, model = "full"), "nmfkc.DOT")
  ## the null draws no feedback edge (Y1 -> Factor) even at a tiny threshold
  expect_false(grepl("Y1_[0-9]+ -> F_", nmf.ffb.DOT(fit, model = "null", threshold = 1e-9)))
  pdf(NULL); on.exit(dev.off(), add = TRUE)
  expect_invisible(plot(fit))

  ## a supplied basis skips stage 1 and reproduces the same stage-2 fit
  fit2 <- nmf.ffb(d$Y1, d$Y2, X = fit)
  expect_equal(fit2$X, fit$X)
  expect_equal(fit2$null$loglik, fit$null$loglik, tolerance = 1e-6)
  ## select = "none" returns the unpenalized fit as the selected model
  fit3 <- nmf.ffb(d$Y1, d$Y2, X = fit$X, select = "none", phi = "diag")
  expect_equal(fit3$C1, fit3$full$C1); expect_equal(nrow(fit3$path), 2)
  expect_true(all(fit3$Phi[upper.tri(fit3$Phi)] == 0))
  ## a user mask is used as given
  fit4 <- nmf.ffb(d$Y1, d$Y2, X = fit$X, mask = matrix(1, 2, 6), lambda1 = c(1, 5))
  expect_equal(unname(fit4$LR.df[["full"]]), 12); expect_equal(nrow(fit4$path), 1 + 3 + 4 + 1)
  ## a subset of starts: one row per (lambda1, start), and the multi-start
  ## selection is never worse (in BIC) than any single start
  fit5 <- nmf.ffb(d$Y1, d$Y2, X = fit$X, starts = "full")
  expect_identical(fit5$starts, "full"); expect_equal(nrow(fit5$path), 2 + 8)
  expect_true(all(fit5$path$start %in% c("full", "null")))
  expect_lte(fit$BIC[["selected"]], fit5$BIC[["selected"]] + 1e-8)
  fit6 <- nmf.ffb(d$Y1, d$Y2, X = fit$X, starts = c("path", "null"))
  expect_identical(fit6$starts, c("path", "null")); expect_equal(nrow(fit6$path), 2 + 1 + 2 * 7)
  expect_error(nmf.ffb(d$Y1, d$Y2, X = fit$X, starts = "random"))
  ## the caller's random stream is left alone
  set.seed(1); a <- runif(1); set.seed(1); invisible(nmf.ffb(d$Y1, d$Y2, rank = 2)); b <- runif(1)
  expect_identical(a, b)
})

test_that("nmf.ffb(method = 'mu') reproduces the pre-fiml estimator", {
  skip_unless_full()
  ## Expected values were captured with nmf.ffb() BEFORE method = "fiml" was
  ## added (2026-09-07, R 4.4.1, Windows; bit-identical in that session).
  Y <- t(iris[, -5]); Y1 <- Y[1:2, ]; Y2 <- Y[3:4, ]
  X <- structure(c(0.99917471938580282, 0.00082528061419721963, 0.0090212281769937244,
                   0.99097877182300631), dim = c(2L, 2L))
  C1 <- structure(c(0.69579132651489872, 0.027988927398813722, 0.35793327504197442,
                    0.95440141876463536), dim = c(2L, 2L))
  C2 <- structure(c(0.17413656755523033, 7.6817175792012538e-07, 0.0017827892538159042,
                    1.28965333216348e-05), dim = c(2L, 2L))
  fit <- suppressWarnings(nmf.ffb(Y1, Y2, rank = 2, maxit = 500, method = "mu"))
  expect_identical(fit$method, "mu")
  expect_identical(tail(names(fit), 1), "method")   # appended, legacy order kept
  expect_equal(unname(fit$X), X, tolerance = 1e-12)
  expect_equal(unname(fit$C1), C1, tolerance = 1e-12)
  expect_equal(unname(fit$C2), C2, tolerance = 1e-12)
  expect_equal(fit$MAE, 1.6921588411103816, tolerance = 1e-12)
  expect_identical(fit$iter, 500L)
  expect_equal(fit$XC1.radius, 0.98224336583946881, tolerance = 1e-12)
  expect_equal(fit$SC.map, 0.99904125606669214, tolerance = 1e-12)
  expect_length(fit$objfunc, 500L)

  ## legacy inference path (full pair bootstrap) is untouched
  inf <- suppressWarnings(nmf.ffb.inference(fit, Y1, Y2, B = 20, epsilon = 1e-6, maxit = 3000,
                                            calibration = "conditional"))
  expect_equal(inf$coefficients$Estimate,
               c(0.69579132651489872, 0.027988927398813722, 0.35793327504197442,
                 0.95440141876463536, 0.17413656755523033, 7.6817175792012538e-07,
                 0.0017827892538159042, 1.28965333216348e-05), tolerance = 1e-12)
  expect_equal(inf$coefficients$CI_low,
               c(0.92553572081069646, 0.0051135714135355295, 0.052587614213536915,
                 0.99472570877034272, 0.033366460045613611, 1.9021882018577706e-09,
                 1.054646350983465e-05, 7.4253001967520671e-10), tolerance = 1e-12)
  expect_equal(inf$coefficients$CI_high,
               c(0.94672483097340177, 0.0065391022854661557, 0.079314340248516024,
                 0.99735786408504867, 0.044316128268452187, 2.1905083084032289e-06,
                 0.00016346448096955804, 5.2989243658185696e-06), tolerance = 1e-12)
  expect_equal(inf$coefficients$support_rate, c(1, 0, 1, 1, 1, 0, 0, 0))
  expect_identical(inf$bootstrap.n.valid, 20L)
  expect_true(!is.null(inf$AR.boot))

  ## nmf.ffb.cv() without `method` still fits the legacy estimator in its folds
  cv <- suppressWarnings(nmf.ffb.cv(Y1, Y2, rank = 2, maxit = 500, nfolds = 3))
  expect_equal(cv, 1.6565815316156454, tolerance = 1e-12)
})

test_that("nmf.ffb.inference() on a fiml fit runs the two parametric bootstraps", {
  skip_unless_full()
  d <- make_ffb_data()
  fit <- nmf.ffb(d$Y1, d$Y2, rank = d$Q)
  inf <- nmf.ffb.inference(fit, d$Y1, d$Y2, B = 5, calibration = "conditional")

  expect_s3_class(inf, "nmf.ffb.inference"); expect_s3_class(inf, "nmf.inference")
  expect_identical(inf$bootstrap.calibration, "conditional")
  ## null bootstrap
  expect_equal(dim(inf$LR.boot), c(5, 2)); expect_equal(colnames(inf$LR.boot), c("full", "selected"))
  expect_named(inf$LR.p.boot, c("full", "selected"))
  expect_true(all(inf$LR.p.boot >= 0 & inf$LR.p.boot <= 1))
  expect_named(inf$LR.null.quantile, c("full", "selected"))
  expect_true(inf$prob.select.null >= 0 && inf$prob.select.null <= 1)
  expect_length(inf$nnz.boot, 5)
  ## selected-model bootstrap
  cf <- inf$coefficients
  expect_true(all(c("Type", "Basis", "Covariate", "Estimate", "CI_low", "CI_high",
                    "support_rate", "p_value", "sig") %in% names(cf)))
  expect_equal(nrow(cf), 2 * 6 + 2 * 2)
  expect_equal(cf$Estimate[cf$Type == "C1"], as.vector(fit$C1))
  expect_equal(cf$Estimate[cf$Type == "C2"], as.vector(fit$C2))
  expect_true(all(cf$support_rate[cf$Type == "C1"][as.vector(fit$support) == FALSE] == 0))
  expect_equal(dim(inf$C1.array), c(5, 2, 6)); expect_equal(dim(inf$C2.array), c(5, 2, 2))
  expect_equal(dim(inf$C1.ci.lower), c(2, 6)); expect_equal(dim(inf$C2.ci.upper), c(2, 2))
  expect_length(inf$rho.boot, 5)
  expect_identical(inf$bootstrap.B, 5L); expect_equal(inf$bootstrap.threshold, 0.01)
  expect_equal(inf$bootstrap.ci.level, 0.95)
  expect_equal(inf$bootstrap.n.valid + inf$bootstrap.n.invalid, 5L)
  ## downstream consumers
  expect_s3_class(nmf.ffb.DOT(inf), "nmfkc.DOT")
  expect_output(print(inf), "Parametric bootstrap under the FF null")
  expect_true(is.data.frame(coef(inf)))
  ## deterministic given the seed, and the caller's stream is untouched
  set.seed(7); a <- runif(1)
  set.seed(7); inf2 <- nmf.ffb.inference(fit, d$Y1, d$Y2, B = 5, calibration = "conditional"); b <- runif(1)
  expect_identical(a, b)
  expect_identical(inf2$LR.boot, inf$LR.boot)
  ## boot.null = FALSE skips the (expensive) null bootstrap
  inf3 <- nmf.ffb.inference(fit, d$Y1, d$Y2, B = 3, boot.null = FALSE, calibration = "conditional")
  expect_null(inf3$LR.boot); expect_null(inf3$LR.p.boot)
  expect_null(inf3$LR.boot.n.nonconv); expect_null(inf3$LR.boot.n.ok)
  expect_equal(nrow(inf3$coefficients), nrow(cf))
})

test_that("the bootstrap LR p-value is never exactly zero and honours its floor", {
  skip_unless_full()
  ## Regression test: LR.p.boot used to be the raw proportion
  ## mean(LR* >= LR_obs), which is exactly 0 whenever no replicate reaches the
  ## observed statistic -- the usual case for a strongly significant fit, and an
  ## invalid p-value.  It is now (1 + #)/(1 + B_ok), floored at 1/(1 + B_ok).
  d <- make_ffb_data()
  fit <- nmf.ffb(d$Y1, d$Y2, rank = d$Q)
  B <- 20L
  inf <- nmf.ffb.inference(fit, d$Y1, d$Y2, B = B, calibration = "conditional")

  expect_true(all(inf$LR.p.boot > 0))
  expect_identical(inf$LR.boot.n.ok, sum(is.finite(inf$LR.boot[, "full"]) &
                                         is.finite(inf$LR.boot[, "selected"])))
  floor.p <- 1 / (1 + inf$LR.boot.n.ok)
  expect_true(all(inf$LR.p.boot >= floor.p - 1e-12))
  ## the value must equal the (1 + #)/(1 + B_ok) count on the stored replicates
  ok <- is.finite(inf$LR.boot[, "full"]) & is.finite(inf$LR.boot[, "selected"])
  expect_equal(unname(inf$LR.p.boot[["full"]]),
               (1 + sum(inf$LR.boot[ok, "full"] >= fit$LR[["full"]])) / (1 + sum(ok)))
  ## convergence counts are reported and cannot exceed the usable replicates
  expect_named(inf$LR.boot.n.nonconv, c("null", "full"))
  expect_true(all(inf$LR.boot.n.nonconv >= 0 & inf$LR.boot.n.nonconv <= inf$LR.boot.n.ok))
})

test_that("the default exclusion mask is the union of the dominant-factor and threshold rules", {
  ## .ffb.fiml.mask() takes the basis as given (nmf.ffb normalises before calling
  ## it), so use the rows as written: normalising here would move the argmax of
  ## row 3 to a loading above the threshold and defeat the third case.
  X <- rbind(c(0.60, 0.30, 0.10),   # dominant 1, loads on 2 above 0.05 -> both blocked
             c(0.02, 0.01, 0.97),   # dominant 3 only
             c(0.03, 0.02, 0.01))   # largest loading below 0.05: "cross" alone would free everything
  M_union <- nmfkc:::.ffb.fiml.mask(X, "union", 0.05)
  M_block <- nmfkc:::.ffb.fiml.mask(X, "block", 0.05)
  M_cross <- nmfkc:::.ffb.fiml.mask(X, "cross", 0.05)
  expect_equal(M_union, M_block * M_cross)
  expect_true(all(M_union <= M_block) && all(M_union <= M_cross))
  ## "cross" is not a superset of "block": outcome 3 keeps its own factor free
  expect_true(any(M_cross > M_block))
  expect_identical(nmfkc:::.ffb.fiml.mask(X, "union"), nmfkc:::.ffb.fiml.mask(X))
  d <- make_ffb_data()
  fit <- nmf.ffb(d$Y1, d$Y2, rank = d$Q)
  expect_identical(fit$mask.rule, "union")
  expect_true(is.list(fit$stage1.args) && isTRUE(fit$stage1.args$from.data))
})

test_that("calibration = 'full' re-estimates the basis and reports mask movement", {
  skip_unless_full()
  d <- make_ffb_data()
  fit <- nmf.ffb(d$Y1, d$Y2, rank = d$Q)
  inf <- nmf.ffb.inference(fit, d$Y1, d$Y2, B = 6, calibration = "full")
  expect_identical(inf$bootstrap.calibration, "full")
  expect_equal(dim(inf$LR.boot), c(6, 2))
  expect_true(is.numeric(inf$mask.change.rate) && inf$mask.change.rate >= 0 && inf$mask.change.rate <= 1)
  expect_length(inf$LR.boot.df, 6)
  expect_true(all(inf$LR.p.boot > 0))
  expect_output(print(inf), "re-estimated on every null replicate")
})

test_that("calibration = 'split' (the default) returns one row per split and direction", {
  skip_unless_full()
  d <- make_ffb_data()
  fit <- nmf.ffb(d$Y1, d$Y2, rank = d$Q)
  inf <- nmf.ffb.inference(fit, d$Y1, d$Y2, B = 4, nsplit = 2)
  expect_identical(inf$bootstrap.calibration, "split")
  st <- inf$split.table
  expect_s3_class(st, "data.frame"); expect_equal(nrow(st), 4)
  expect_setequal(st$direction, c("AB", "BA"))
  expect_true(all(c("split", "N_est", "N_test", "df", "LR_full", "LR_selected", "nnz_selected",
                    "p_full", "p_selected", "null_q95_full", "prob_select_null", "B_ok") %in% names(st)))
  expect_true(all(st$N_est + st$N_test == ncol(d$Y1)))
  expect_true(all(st$p_full > 0 & st$p_full <= 1))
  ## no single p-value is defined at this level
  expect_null(inf$LR.p.boot); expect_null(inf$prob.select.null)
  ## coefficient CIs (conditional on the full-sample fit) are still produced
  expect_true(is.data.frame(inf$coefficients))
  expect_output(print(inf), "sample splitting")
  ## a user-supplied mask cannot be re-derived: falls back with a warning
  fitU <- nmf.ffb(d$Y1, d$Y2, rank = d$Q, mask = fit$mask)
  expect_warning(infU <- nmf.ffb.inference(fitU, d$Y1, d$Y2, B = 3, calibration = "full"), "falling back")
  expect_identical(infU$bootstrap.calibration, "conditional")
})

test_that("nmf.ffb.cv(method = 'fiml') delegates to nmfkc.ecv()", {
  skip_unless_full()
  d <- make_ffb_data()
  e <- suppressMessages(nmf.ffb.cv(d$Y1, d$Y2, rank = 1:2, method = "fiml", nfolds = 3))
  expect_s3_class(e, "nmfkc.ecv")
  expect_length(e$objfunc, 2)
  expect_true(all(is.finite(e$objfunc)))
})
